steps:
  - id: "Executar os testes"
    name: "gcr.io/cloud-builders/go:alpine"
    args: ["test", "./..."]
    env:
      - "GOPATH=/go/src/app/src"

  - id: "Build da imagem"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/go_hpa:$SHORT_SHA", "."]

  - id: "Push da imagem"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/go_hpa:$SHORT_SHA"]

  - id: "Ajustando Deployment do App no k8s"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/go_hpa:$SHORT_SHA#g' k8s/deployment.yaml > k8s/deployment-new.yaml;
        cat k8s/deployment-new.yaml

  - id: "Deploy no k8s"
    name: "gcr.io/cloud-build/kubectl"
    args:
      - "apply"
      - "-f"
      - "k8s/deployment-new.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=go-hpa-cluster"
