apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hpa
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-hpa
  targetCPUUtilizationPercentage: 15

  # Testing autoscaler
  # kubectl run -it --rm load-generator --image=busybox /bin/sh
  # while true; do wget -q -O- http://go-hpa-service.default.svc.cluster.local:8000; done;
